import { NextRequest, NextResponse } from "next/server";
import type { NormalizedIntake } from "../intake/route";
import type { ConservatorshipPlan } from "@/types/plan";

type PacketRequest = {
  intake: NormalizedIntake;
  plan: ConservatorshipPlan;
};

export async function POST(req: NextRequest) {
  const body = (await req.json()) as PacketRequest;
  const { intake, plan } = body;

  const text = buildLawyerPacket(intake, plan);

  return new NextResponse(text, {
    status: 200,
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Content-Disposition":
        "attachment; filename=conservatorship_summary_for_lawyer.txt",
    },
  });
}

function buildLawyerPacket(
  intake: NormalizedIntake,
  plan: ConservatorshipPlan
): string {
  const person = intake.person;
  const petitioner = intake.petitioner;

  const header = [
    "Conservatorship Summary for Tennessee Attorney",
    "==============================================",
    "",
    "This summary was generated by an information-only tool. It is not legal advice.",
    "Please review, correct, and supplement based on Tennessee law and local court practice.",
    "",
  ].join("\n");

  const basics = [
    "1. Basic case information",
    "-------------------------",
    `Person with a disability (respondent): ${person.name || "[name not provided]"}`,
    `Age: ${person.age ?? "[age not provided]"}`,
    `City / County: ${person.city || "[city]"}, ${person.county || "[county]"}`,
    `Conditions / diagnoses (family-reported): ${
      person.conditions.join(", ") || "[none listed]"
    }`,
    `Petitioner / relation: ${petitioner.relation || "[relation not provided]"}`,
    "",
    `Stated goals: ${intake.goals || "[no goals description provided]"}`,
    `Alternatives tried or considered: ${
      intake.alternatives_tried || "[not described]"
    }`,
    `Main concerns: ${intake.concerns.join(", ") || "[none selected]"}`,
    "",
  ].join("\n");

  const summary = [
    "2. High-level summary (from tool)",
    "---------------------------------",
    plan.summary,
    "",
  ].join("\n");

  const infoToGather = [
    "3. Information and documents to gather",
    "--------------------------------------",
    ...plan.buckets.info_to_gather,
    "",
  ].join("\n");

  const filing = [
    "4. Filing-related notes (for your review)",
    "-----------------------------------------",
    ...plan.buckets.filing_requirements,
    "",
  ].join("\n");

  const duties = [
    "5. Conservator duties (if appointed)",
    "------------------------------------",
    ...plan.buckets.duties_after,
    "",
  ].join("\n");

  const documentation = [
    "6. Documentation and recording practices",
    "----------------------------------------",
    ...plan.buckets.documentation_and_recording,
    "",
  ].join("\n");

  const memphisHelp = [
    "7. Local context and contacts (Memphis / Shelby)",
    "-----------------------------------------------",
    ...plan.buckets.memphis_shelby_help,
    "",
  ].join("\n");

  const petitionDraft = [
    "8. Draft petition language (for attorney review only)",
    "-----------------------------------------------------",
    "Intro:",
    plan.petition_sections.intro,
    "",
    "Facts (tool-generated skeleton):",
    plan.petition_sections.facts,
    "",
    "Requested powers (areas to discuss with the court):",
    plan.petition_sections.requested_powers,
    "",
    "Less restrictive options (as described by family):",
    plan.petition_sections.less_restrictive_explained,
    "",
  ].join("\n");

  const disclaimers = [
    "9. Safety and disclaimer (from tool)",
    "------------------------------------",
    ...plan.buckets.safety_and_disclaimer,
    "",
    "Please treat this entire packet as unverified client intake material,",
    "not as a legal document ready for filing.",
    "",
  ].join("\n");

  return [
    header,
    basics,
    summary,
    infoToGather,
    filing,
    duties,
    documentation,
    memphisHelp,
    petitionDraft,
    disclaimers,
  ].join("\n");
}
